name: KMP Artifacts

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  xcframework:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build XCFramework
        run: |
          ./gradlew :shared:clean :shared:linkDebugFrameworkIosArm64 :shared:linkDebugFrameworkIosX64 :shared:linkDebugFrameworkIosSimulatorArm64
          
          # Create XCFramework directory
          mkdir -p shared/build/XCFrameworks/debug
          
          # Create XCFramework using xcodebuild
          xcodebuild -create-xcframework \
            -framework shared/build/bin/iosArm64/debugFramework/shared.framework \
            -framework shared/build/bin/iosX64/debugFramework/shared.framework \
            -framework shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework \
            -output shared/build/XCFrameworks/debug/Shared.xcframework
        
      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shared.xcframework
          path: shared/build/XCFrameworks/debug/Shared.xcframework
          retention-days: 30
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Run shared tests
        run: ./gradlew :shared:test
        
      - name: Run server tests
        run: ./gradlew :server:test
        
      - name: Run web tests
        run: ./gradlew :web:test

