name: KMP Artifacts

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  xcframework:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Build XCFramework
        run: ./gradlew :shared:clean :shared:assembleXCFramework
        
      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shared.xcframework
          path: shared/build/XCFrameworks/**/Shared.xcframework
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Run tests
        run: ./gradlew :shared:test :server:test
